from typing import Literal, Optional
from pydantic import BaseModel, Field



class WorkflowContext(BaseModel):
    ## storage
    # 1. optimize prompt
    user_task: str = Field(default="", description="User input task")
    context: str = Field(default="", description="User input context")
    optimized_prompt: str = Field(default="", description="Optimized prompt based on user task")
    cron_expression: str = Field(default=None, description="Cron expression for scheduling")
    workflow_id: str = Field(default=None, description="Workflow ID")
    prompt_opt_review_feedback: list = Field(default=[], description="review_optimize_agent feedback")

    # 2. workflow tasks generate
    planned_workflow_steps: list = Field(default=[], description="Planned workflow steps")
    pending_agentic_steps: list = Field(default=[], description="Pending agentic steps")
    pending_script_steps: list = Field(default=[], description="Pending script steps")
    agentic_generated_results: dict = Field(default={}, description="Agentic step results")
    script_generated_results: dict = Field(default={}, description="Script step results")
    completed_workflow_steps: list = Field(default=[], description="Completed workflow steps")
    review_feedback: list = Field(default=[], description="Review agent feedback")
    final_workflow_tasks: str = Field(default="", description="Final completed workflow tasks")


    ## processing state
    # 1. optimize prompt
    task_is_received: bool = Field(default=False, description="Whether the user task is received")
    prompt_is_optimized: bool = Field(default=False, description="Whether the user task is optimized")
    is_valid_cron: bool = Field(default=False, description="Whether the cron expression is valid")
    prompt_needs_revision: bool = Field(default=True, description="Whether optimized prompt needed revision")
    prompt_revision_count: int = Field(default=0, description="Prompt revision count")
    max_prompt_revisions: int = Field(default=10, description="Maximum number of prompt revisions")
    prompt_review_is_completed: bool = Field(default=False, description="Whether review_prompt_agent is completed")

    # 2. workflow tasks generate
    plan_is_generated: bool = Field(default=False, description="Whether the plan is generated")
    input_output_consistent: bool = Field(default=False, description="Whether input and output of interdependent steps are consistent")
    is_DAG: bool = Field(default=False, description="Is DAG structure")
    all_steps_results_collect_complete: bool = Field(default=False, description="Whether all step results collection is complete")
    merge_workflow_steps_completed: bool = Field(default=False, description="Whether the steps are merged")
    needs_revision: bool = Field(default=True, description="Whether revision is needed")
    review_is_completed: bool = Field(default=False, description="Whether review is completed")
    max_revisions: int = Field(default=10, description="Maximum number of revisions")
    revision_count: int = Field(default=0, description="Revision count")
    ready_for_write: bool = Field(default=False, description="Whether ready for writing")
    final_workflow_tasks_is_generated: bool = Field(default=False, description="Whether final JSON is generated")
    workflow_tasks_generated_count: int = Field(default=0, description="The number of workflow steps generated by plan_agent")

    # 3. log anomaly analysis (15w logs)
    raw_log_task: str = Field(default="", description="Original instruction for log analysis task")
    raw_log_metadata: dict = Field(default={}, description="Parsed metadata about the log source")
    chunk_dispatch_plan: list = Field(default=[], description="Chunk dispatch plan with 10k line windows")
    pending_chunks: list = Field(default=[], description="Queue of chunk identifiers pending processing")
    processed_chunks: list = Field(default=[], description="Chunk identifiers already processed")
    inflight_chunk_id: str = Field(default="", description="Chunk currently being processed")
    llm_split_requests: dict = Field(default={}, description="Prompt payloads sent to the LLM per chunk")
    chunk_summaries: dict = Field(default={}, description="Intermediate summaries returned by the LLM per chunk")
    preaggregated_windows: dict = Field(default={}, description="Window-level aggregation results")
    anomaly_signals: list = Field(default=[], description="Detected anomaly signals across windows")
    issue_hypotheses: list = Field(default=[], description="Hypotheses describing potential issues")
    validation_reports: list = Field(default=[], description="Validation reports confirming or challenging hypotheses")
    final_findings: list = Field(default=[], description="Final confirmed findings")
    report_content: str = Field(default="", description="Final report content for downstream consumption")

    ## processing state for log analysis
    log_task_received: bool = Field(default=False, description="Whether the log analysis task has been received")
    log_metadata_ready: bool = Field(default=False, description="Whether log metadata has been parsed")
    ingest_ready: bool = Field(default=False, description="Whether ingest checks are completed")
    chunk_plan_ready: bool = Field(default=False, description="Whether the chunk dispatch plan is ready")
    chunk_processing_complete: bool = Field(default=False, description="Whether all chunk summaries are prepared")
    preaggregation_complete: bool = Field(default=False, description="Whether pre-aggregation is complete")
    anomaly_analysis_complete: bool = Field(default=False, description="Whether anomaly identification is complete")
    validation_complete: bool = Field(default=False, description="Whether validation stage is complete")
    needs_rechunk: bool = Field(default=False, description="Whether chunks need to be regenerated")
    needs_rescan: bool = Field(default=False, description="Whether anomaly detection needs to be rerun")
    ready_for_report: bool = Field(default=False, description="Whether findings are ready for reporting")
    final_report_generated: bool = Field(default=False, description="Whether the final report has been generated")
    llm_chunk_size: int = Field(default=10000, description="Chunk size to stream into the LLM")
